### ISSUE TITLE
Automated Student Email Logging

### ISSUE THREAD

**Issue by tjhubz** [tjhubz/PittBOT#2]
**Target date**: August 10th, 2022
**Bounty**: $40

This is a simple email logging feature for accountability

### Required Functionality
> This feature must work in tandem with issue #1 

1. Upon joining the server, users will only have access to a verification channel.
    - The bot will already have a record of their user id within a database as discussed in issue #1.
    - Instead of immediately assigning them the community role, it will wait until the verification process is complete.
    
2. In this channel, users will enter a /verify command. It will then pop up a discord modal survey
   - https://docs.pycord.dev/en/master/api.html?highlight=modal#discord.ui.Modal

4. Within the modal, they will be prompted to enter their @pitt.edu email. The bot will log this email in the database for their discord user ID.
    - If they enter an email that doesn't end with @pitt.edu, it will tell them to try again.

5. It will set their discord username to be the pitt email they sent. Minus the "@pitt.edu"
    - For example, thh43@pitt.edu will become thh43
    - This will prevent issues with existing discord usernames

6. Then, it will assign them the community role that they were supposed to have as a result of using an invite link from issue #1.
   - As a result of this they will no longer have access to the verify channel.

7. A database query command should be available to look up emails for a discord user id.
   - /lookup (userid)

**Comment by Elsklivet** [comment]
Started in 8a8f8aa2e8555f82dc1b810a83112ba6bc0b7bf3

Modal is sent in DM (for user convenience) and can be initiated in verification channel. and email is collected and placed in database. Other functionality not started yet.

**Comment by tjhubz** [comment]
Great work!
