### ISSUE TITLE
set_ra command cannot find user_ids

### ISSUE THREAD

**Issue by tjhubz** [tjhubz/PittBOT#22]
When using the /set_ra command with a valid user id, it cannot find the ra. No errors in console.

**Comment by Elsklivet** [comment]
Does this mean the command isn't finding the RA role? No role is assigned? Database isn't updated?

Not sure what is going wrong here.

**Comment by Elsklivet** [comment]
I think this  has been fixed with 8495a0ad3489cef3a860b0c2f6590e80ed1ac4b5. Closing for now. If the issue arises again, re-open.
