### ISSUE TITLE
Non-urgent error thrown in console if user does not fill out modal in time

### ISSUE THREAD

**Issue by tjhubz** [tjhubz/PittBOT#23]
If a user clicks the verification button and does not enter an email in time/cancels the interaction the bot throws an error in console. This is non-feature breaking as far as I know.

**Comment by Elsklivet** [comment]
Minimized in c4268812e861230a3c3691c63dae3f70208b012f, but `RuntimeWarning` still appears, although it is very small. Cannot find good documentation to fix this. Setting as low priority for now.
