### ISSUE TITLE
Add help link to verify message

### ISSUE THREAD

**Issue by tjhubz** [tjhubz/PittBOT#34]
If there could be another button added to the verify message that directed users to [this link](https://pitt.co1.qualtrics.com/jfe/form/SV_25Y15jZ9BmYYEf4) it could help users that are having issues get support.

**Comment by Elsklivet** [comment]
In addition to adding this link to the verify message, it would be helpful to add it to any messages that include something along the lines of "let your RA know!" or "please ask for help!".
