### ISSUE TITLE
Use GitHub actions to automatically build and push the image to Docker registry

### ISSUE THREAD

**Issue by tjhubz** [tjhubz/PittBOT#38]
Currently, the PittBOT image is being built on a private Jenkins server manually. Since we have access to GitHub Actions for free, we should transition to using it instead of Jenkins in order to simplify the process.

Upon a push to the main branch, it should build and push the image with the tjhubz/pittbot:latest and tjhubz/pittbot:(version) tags. It will then state if the build is successful for easy continuous deployment.

**Comment by Elsklivet** [comment]
Looks like a good option to start: [Build and Push Docker Images](https://github.com/marketplace/actions/build-and-push-docker-images)

**Comment by vrr11** [comment]
We learned Docker and GitHub Actions in 1632, I'll take a look at this once I finish with the FAQ.

**Comment by tjhubz** [comment]
@vrr11 Did you get a chance to check this out?

**Comment by vrr11** [comment]
Not yet, I've been busy with classes starting

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
