### ISSUE TITLE
Automatic FAQ system

### ISSUE THREAD

**Issue by tjhubz** [tjhubz/PittBOT#4]
**Target Date**: none

There are a lot of common questions that are asked by residents. To ensure that they get a timely response, it would be great if the PittBOT could automatically answer these questions helpfully. There are bots that can do this already, but the key is ease of use. The bot should not require a command for the bot to answer a question - if possible, it would have natural language interpretation. Obviously, that's a difficult task, so in the meantime it could have exact word match responses.

### Required Functionality
1. RAs and other admin staff can set questions and answers using a command.
    - Command format: https://i.imgur.com/BNlxr9z.png (up for debate)
    
2. If a user types that question in chat, the bot will automatically respond with the answer as defined.
> Example response: Hey there! I found this answer that might help you: (answer)

**Comment by vrr11** [comment]
Have explicit `/faq` command functionality working, no progress on NLP-based responses.

**Comment by tjhubz** [comment]
Implemented
