### ISSUE TITLE
Automatic Slur/Nudity Prevention and Notifications

### ISSUE THREAD

**Issue by tjhubz** [tjhubz/PittBOT#5]
Target Date: August 10th, 2022

This one is pretty self explanatory, but the execution is slightly different from other bots with this same functionality.

### Required Functionality
1. Undesirable phrases will be defined in a plaintext config file within the bot.

2. If a user says a banned phrase, the bot triggers.
    - If an image is sent it will use the [SafeSearch API](https://cloud.google.com/vision/docs/detecting-safe-search) to scan the image for adult content. API Keys should be environment variables.

4. It sends a detail message to the control server log channel.

3. It will timeout the user for 12h

5. It will lookup the user id in the database and find which community they belong to (aka which community role they have)

6. It will then DM the RA associated with that community with details of who the user is and what they did. 

7. It will give the RA the option to permanently time out the user or mark this issue as a false flag.

8. Depending on what the RA chose to do about the issue, it will update the message in the log channel mentioned in step 3.

**Comment by Elsklivet** [comment]
Step 5 does not need database access. The API allows for roles a user is assigned to be fetched, the community can be acquired immediately. 

To DM the RA, the bot will likely have to fetch all of the members of the guild and find one with both the same community role as well as an "RA" named role. This operation is potentially slow. 

Steps 7 and beyond are **bad design choices**, as the RAs can very easily manually untimeout or extend a timeout on a user once they've been notified, without the necessity of adding further error surface area and sending evaporated interactions around different functions, which is abuse of the discord API.

If it is essential that steps 7+ are added, **developers should use temporary caches** to achieve the functionality, not passing interactions around.

**Comment by tjhubz** [comment]
Discord implemented directly
